const fs = require('fs');
const path = require('path');

const glslDir = path.join(__dirname, 'Anime4K', 'glsl');
const outputFile = path.join(__dirname, 'src', 'shaders-data.js');

function getAllGlslFiles(dir, fileList = []) {
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const filePath = path.join(dir, file);
    if (fs.statSync(filePath).isDirectory()) {
      getAllGlslFiles(filePath, fileList);
    } else if (filePath.endsWith('.glsl')) {
      fileList.push(filePath);
    }
  }
  return fileList;
}

const shaderFiles = getAllGlslFiles(glslDir);
const shadersData = {};

for (const filePath of shaderFiles) {
  const fileName = path.basename(filePath);
  const content = fs.readFileSync(filePath, 'utf8');
  shadersData[fileName] = content;
}

const fileContent = `// Automatically generated by build-shaders.js
export const shadersData = ${JSON.stringify(shadersData, null, 2)};
`;

fs.writeFileSync(outputFile, fileContent, 'utf8');
console.log(`Successfully built shaders data. Included ${shaderFiles.length} files.`);
