import os
import json

base_dir = os.path.dirname(os.path.abspath(__file__))
glsl_dir = os.path.join(base_dir, 'Anime4K', 'glsl')
output_file = os.path.join(base_dir, 'src', 'shaders-data.js')

shaders_data = {}

for root, dirs, files in os.walk(glsl_dir):
    for file in files:
        if file.endswith('.glsl'):
            file_path = os.path.join(root, file)
            with open(file_path, 'r', encoding='utf-8') as f:
                shaders_data[file] = f.read()

file_content = f"// Automatically generated by build-shaders.py\nexport const shadersData = {json.dumps(shaders_data, indent=2)};\n"

with open(output_file, 'w', encoding='utf-8') as f:
    f.write(file_content)

print(f"Successfully built shaders data. Included {len(shaders_data)} files.")
